name: CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker build -t ghcr.io/xannexed11/rabotenka:1.0 .
      - run: docker push ghcr.io/xannexed11/rabotenka:1.0
      - run: ssh -o "StrictHostKeyChecking no" 'xannexed11-rabotenka-r5h6zmkx761#bgwbxWdrnvoDCmN8mLz..ECaOBfaKZSI@xannexed11-rabotenka-r5h6zmkx761.ssh.ws-eu106.gitpod.io' 'cd /workspace/rabotenka && docker compose pull && docker compose up -d'
  
